### ISSUE TITLE
1 Pity Navia

### ISSUE THREAD

**Issue by leafpool243** [dval-in/dvalin-backend#109]
![圖片](https://github.com/dval-in/dvalin-frontend/assets/63614345/272906cc-c488-47e5-a50d-962dcd13b3f9)

The website shows me as having obtained Navia at 1 pity when that clearly isn’t the case.

(I mentioned this on the Discord, but thought this would be the better place to put it long-term.)

**Comment by maalni** [comment]
Moved this to backend

**Comment by MasterLegend2772** [comment]
Thanks maalni

**Comment by leafpool243** [comment]
> This issue should be already resolved for new data. Older data needs to be migrated manually. Will leave this open until older data was migrated.
@maalni So has it been migrated?  Navia still displays as 1 pity for me.

**Comment by LudovicMalot** [comment]
> > This issue should be already resolved for new data. Older data needs to be migrated manually. Will leave this open until older data was migrated.
> > @maalni So has it been migrated?  Navia still displays as 1 pity for me.

a new version will come, currently in testing. Importing from paimon should resolve the issue. 
if u can't/ dont want to import, we'll do it manually for u
